title: toy2do
email: magdalena@toy2do.com
description: toy2do.com
baseurl: ""
url: "https://toy2do.com" # the base hostname & protocol for your site
markdown: kramdown
exclude: [Gemfile, Gemfile.lock]
